name: Tests
on: [push]
jobs:
    lint:
        name: test
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.7'
            - run: make
            - run: python setup.py test
